### ISSUE TITLE
Maven support

### ISSUE THREAD

**Issue by aliakhtar** [upwork/java-upwork#3]
Hey. Could you please add maven support for this?

Thanks.

**Comment by mnovozhylov** [comment]
@aliakhtar , we've added pom.xml
In case you need more, create a pull request with proposed changes and we will review it.

**Comment by aliakhtar** [comment]
What about publishing to central?

**Comment by mnovozhylov** [comment]
@aliakhtar , it's been populated
please use the following with Maven:
```
<dependency>
    <groupId>com.Upwork</groupId>
    <artifactId>api</artifactId>
    <version>1.0.1</version>
</dependency>
```
